### ISSUE TITLE
ZeroDivisionError during training

### ISSUE THREAD

**Issue by DarkMarkZX** [yuxumin/PoinTr#101]
Hi,
I followed Issue #11 and made several attempts at training PoinTr on custom data: first for my own dataset (using PCN structure), then for a small subset of PCN data, and finally for a subset of ShapeNet-55. Each time I run the train script, I get the following error:
```
PoinTrC - INFO - Using Data parallel ...
/home/darkmark/anaconda3/envs/proxyformer/lib/python3.7/site-packages/torch/optim/lr_scheduler.py:134: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  "https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate", UserWarning)
Traceback (most recent call last):
  File "main.py", line 68, in <module>
    main()
  File "main.py", line 64, in main
    run_net(args, config, train_writer, val_writer)
  File "/home/darkmark/Documents/Python/PoinTr/PoinTr-master/tools/runner.py", line 165, in run_net
    train_writer.add_scalar('Loss/Epoch/Sparse', losses.avg(0), epoch)
  File "/home/darkmark/Documents/Python/PoinTr/PoinTr-master/utils/AverageMeter.py", line 42, in avg
    return self._sum[idx] / self._count[idx]
ZeroDivisionError: division by zero
```
Is there any way to fix this? I have no trouble running the pretrained models, but I would like to train PoinTr on outdoor buildings data.

**Comment by yuxumin** [comment]
This error comes from AverageMeter, for trying calculate the average for a empty loss list.
So can you check if you update values for `losses` during your training loop?

**Comment by DarkMarkZX** [comment]
@yuxumin Thank you for the quick reply.
It appears that the `losses` are never calculated in the first place, because for some reason `n_batches` is 0. I have no idea why - the config files are read properly, and the data files are loaded as well:
```
[DATASET] Open file data/ShapeNet55-34/ShapeNet-55-c/train.txt
[DATASET] 6 instances were loaded
[DATASET] Open file data/ShapeNet55-34/ShapeNet-55-c/test.txt
[DATASET] 4 instances were loaded
```

**Comment by DarkMarkZX** [comment]
@yuxumin 
Sadly, two years later I am still facing this issue. My goal is to finetune the AdaPoinTr model on a custom dataset, but the process fails even when I use a small subset of the original PCN data and place all the files directly in data/PCN/, eliminating the risk of incorrect data configuration. I run training on a single GPU like this:
```
bash ./scripts/train.sh 0 \
    --config ./cfgs/PCN_models/AdaPoinTr.yaml \
    --exp_name train_pcn \
    --start_ckpts ./pretrained/AdaPoinTr/PCN/AdaPoinTr_PCN.pth
```
but I always get the ZeroDivisionError, which is caused by the fact that _n_batches_ (the length of train_dataloader) is 0. This happens despite the fact that the print logs in PCNcsDataset.py display expected values:
```
Collecting files of Taxonomy [ID=02691156, Name=airplane]
Complete collecting files of the dataset. Total files: 4
```
The contents of the _file_list_ in PCNcsDataset.py also appear to be correct, the beginning looks like this:
"[{'taxonomy_id': '02691156', 'model_id': '1a04e3eab45ca15dd86060f189eb133', 'partial_path': ['data/PCN/train/partial/02691156/1a04e3eab45ca15dd86060f189eb133/00.pcd', "

This does not seem to be a platform problem, since I am able to successfully run the inference scripts on two different machines. I uploaded my minimalistic PCN dataset [here](https://drive.google.com/file/d/1Wh-n_TTJF5dqUQzMnH2c665GJR24Osxp/view?usp=sharing).

Any help would be greatly appreciated. As a side note, I am working on a method of applying existing point cloud completion models to dense point cloud data and I am open to scientific collaboration.
