### ISSUE TITLE
你好，demo下的目录结构应该是如何？

### ISSUE THREAD

**Issue by ao216** [yuxumin/PoinTr#122]
这是我的目录架构，代码报错：没有读到数据
│demo/
├──inference_result/
│   ├──input.npy/
│   ├──05.txt/
│   ├──03.pcd/

/home/testNet/pointr12_9channels# python tools/inference.py cfgs/PCN_models/PoinTr.yaml ckpts/ckpt-best.pth --pc_root demo/ --save_vis_img --out_pc_root inference_result/
2023-08-29 16:02:31,678 - MODEL - INFO -  Transformer with knn_layer 1
Loading weights from ckpts/ckpt-best.pth...
ckpts @ 271 epoch( performance = {'F-Score': 0.4222387577012507, 'CDL1': 32.64521745344003, 'CDL2': 3.8392231023559966})
253453
 demo/inference_result
Traceback (most recent call last):
  File "tools/inference.py", line 120, in <module>
    main()
  File "tools/inference.py", line 115, in main
    inference_single(base_model, pc_file, args, config, root=args.pc_root)
  File "tools/inference.py", line 58, in inference_single
    pc_ndarray = IO.get(pc_file).astype(np.float32)
  File "/home/testNet/pointr12_9channels/tools/../datasets/io.py", line 22, in get
    raise Exception('Unsupported file extension: %s' % (file_extension, file_path))
TypeError: not all arguments converted during string formatting

**Comment by yuxumin** [comment]
你好，我建议你在自己的环境和代码下做debug，看看这一行[here](https://github.com/yuxumin/PoinTr/blob/master/tools/inference.py#L113)
这种简单的bug其实你可以试试自己解决的。

**Comment by ao216** [comment]
明白了，谢谢
