### ISSUE TITLE
How do I run this network to solve AttributeError: 'NoneType' object has no attribute 'items'

### ISSUE THREAD

**Issue by mostafa501** [yuxumin/PoinTr#128]
Hi @yuxumin, thank you for publishing this excellent work, I tried to use this model to complete my partial collected own dara.
I installed all the required libraries and solved the faced problems with previous issues. Simply i tried to inference the demo data using ("python tools/inference.py cfgs/PCN_models/AdaPoinTr.yaml ckpts/AdaPoinTr_PCN.pth --pc_root demo/ --save_vis_img --out_pc_root inference_result/") as illustrated. 
However, I got this error:
_________
(pointr) navlab@navlab-ProLiant-DL380-Gen10:/media/navlab/GNSS/work/pc_completion/Pointtr_net$ python tools/inference.py cfgs/PCN_models/AdaPoinTr.yaml ckpts/AdaPoinTr_PCN.pth --pc_root demo/ --save_vis_img --out_pc_root inference_result/
Traceback (most recent call last):
  File "tools/inference.py", line 120, in <module>
    main()
  File "tools/inference.py", line 105, in main
    config = cfg_from_yaml_file(args.model_config)
  File "/media/navlab/GNSS/work/pc_completion/Pointtr_net/tools/../utils/config.py", line 44, in cfg_from_yaml_file
    merge_new_config(config=config, new_config=new_config)        
  File "/media/navlab/GNSS/work/pc_completion/Pointtr_net/tools/../utils/config.py", line 19, in merge_new_config
    for key, val in new_config.items():
AttributeError: 'NoneType' object has no attribute 'items'
(pointr) navlab@navlab-ProLiant-DL380-Gen10:/media/navlab/GNSS/work/pc_completion/Pointtr_net$
__________

Please help me to solve it, so I can test my own data after that.
Waiting your reply.

**Comment by notniuniu** [comment]
哥们儿，我也遇到了，我调试了一下，发现是因为我自己把dataset的配置文件改动了，导致它没读取到，建议不要加任何词条在dataset的配置文件里，注释也不要加
