### ISSUE TITLE
关于自制kitti数据集训练的问题

### ISSUE THREAD

**Issue by yuluoxingchen111** [yuxumin/PoinTr#150]
您好，我是一名这方面的小白，在尝试用自己制作的kitti数据集进行训练时出现了以下问题：
/root/miniconda3/envs/a/lib/python3.7/site-packages/torch/optim/lr_scheduler.py:136: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  "https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate", UserWarning)
Traceback (most recent call last):
  File "main.py", line 69, in <module>
    main()
  File "main.py", line 65, in main
    run_net(args, config, train_writer, val_writer)
  File "/root/autodl-tmp/pt/tools/runner.py", line 166, in run_net
    train_writer.add_scalar('Loss/Epoch/Sparse', losses.avg(0), epoch)
  File "/root/autodl-tmp/pt/utils/AverageMeter.py", line 42, in avg
    return self._sum[idx] / self._count[idx]
ZeroDivisionError: division by zero
我看到在另一个相同的问题中您提到修改bs，请问这里的bs指的是配置文件中的total_bs吗？如果是的话，我修改成4之后还是会报相同的错误，请问能更详细的解释一下吗？

**Comment by shf0127** [comment]
同学，请问解决了么
