### ISSUE TITLE
Failed to load image Python extension, Open3D Warning

### ISSUE THREAD

**Issue by LeiKeRrr** [yuxumin/PoinTr#24]
Hi ! 

After issue #21 I had a new error when running the same command (test PoinTr model on the PCN benchmark). 

`C:\Repos\PoinTr-master>bash
pierrot@DESKTOP-FMMUKS2:/mnt/c/Repos/PoinTr-master$ bash ./scripts/test.sh 0 \
     --ckpts ./pretrained/PoinTr_PCN.pth \
     --config ./cfgs/PCN_models/PoinTr.yaml \
     --exp_name example
+ GPUS=0
+ PY_ARGS='--ckpts ./pretrained/PoinTr_PCN.pth --config ./cfgs/PCN_models/PoinTr.yaml --exp_name example'
+ CUDA_VISIBLE_DEVICES=0
+ /mnt/c/Users/peter/AppData/Local/Programs/Python/Python36/python.exe main.py --test --ckpts ./pretrained/PoinTr_PCN.pth --config ./cfgs/PCN_models/PoinTr.yaml --exp_name example
C:\Users\peter\AppData\Local\Programs\Python\Python36\lib\site-packages\torchvision\io\image.py:11: UserWarning: Failed
to load image Python extension: [WinError 126] Le module spécifié est introuvable
  warn(f"Failed to load image Python extension: {e}")
'cp' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.
2021-12-17 09:35:10,418 - PoinTr - INFO - Copy the Config file from ./cfgs/PCN_models/PoinTr.yaml to ./experiments\PoinTr\PCN_models\test_example\config.yaml
2021-12-17 09:35:10,419 - PoinTr - INFO - args.config : ./cfgs/PCN_models/PoinTr.yaml
2021-12-17 09:35:10,419 - PoinTr - INFO - args.launcher : none
2021-12-17 09:35:10,419 - PoinTr - INFO - args.local_rank : 0
2021-12-17 09:35:10,420 - PoinTr - INFO - args.num_workers : 4
2021-12-17 09:35:10,420 - PoinTr - INFO - args.seed : 0
2021-12-17 09:35:10,420 - PoinTr - INFO - args.deterministic : False
2021-12-17 09:35:10,421 - PoinTr - INFO - args.sync_bn : False
2021-12-17 09:35:10,421 - PoinTr - INFO - args.exp_name : test_example
2021-12-17 09:35:10,421 - PoinTr - INFO - args.start_ckpts : None
2021-12-17 09:35:10,422 - PoinTr - INFO - args.ckpts : ./pretrained/PoinTr_PCN.pth
2021-12-17 09:35:10,422 - PoinTr - INFO - args.val_freq : 1
2021-12-17 09:35:10,422 - PoinTr - INFO - args.resume : False
2021-12-17 09:35:10,423 - PoinTr - INFO - args.test : True
2021-12-17 09:35:10,423 - PoinTr - INFO - args.mode : None
2021-12-17 09:35:10,423 - PoinTr - INFO - args.experiment_path : ./experiments\PoinTr\PCN_models\test_example
2021-12-17 09:35:10,424 - PoinTr - INFO - args.tfboard_path : ./experiments\PoinTr\PCN_models\TFBoard\test_example
2021-12-17 09:35:10,424 - PoinTr - INFO - args.log_name : PoinTr
2021-12-17 09:35:10,424 - PoinTr - INFO - args.use_gpu : True
2021-12-17 09:35:10,425 - PoinTr - INFO - args.distributed : False
2021-12-17 09:35:10,425 - PoinTr - INFO - config.optimizer = edict()
2021-12-17 09:35:10,425 - PoinTr - INFO - config.optimizer.type : AdamW
2021-12-17 09:35:10,426 - PoinTr - INFO - config.optimizer.kwargs = edict()
2021-12-17 09:35:10,426 - PoinTr - INFO - config.optimizer.kwargs.lr : 0.0005
2021-12-17 09:35:10,426 - PoinTr - INFO - config.optimizer.kwargs.weight_decay : 0.0005
2021-12-17 09:35:10,426 - PoinTr - INFO - config.scheduler = edict()
2021-12-17 09:35:10,427 - PoinTr - INFO - config.scheduler.type : LambdaLR
2021-12-17 09:35:10,427 - PoinTr - INFO - config.scheduler.kwargs = edict()
2021-12-17 09:35:10,427 - PoinTr - INFO - config.scheduler.kwargs.decay_step : 21
2021-12-17 09:35:10,429 - PoinTr - INFO - config.scheduler.kwargs.lr_decay : 0.9
2021-12-17 09:35:10,430 - PoinTr - INFO - config.scheduler.kwargs.lowest_decay : 0.02
2021-12-17 09:35:10,430 - PoinTr - INFO - config.bnmscheduler = edict()
2021-12-17 09:35:10,430 - PoinTr - INFO - config.bnmscheduler.type : Lambda
2021-12-17 09:35:10,431 - PoinTr - INFO - config.bnmscheduler.kwargs = edict()
2021-12-17 09:35:10,431 - PoinTr - INFO - config.bnmscheduler.kwargs.decay_step : 21
2021-12-17 09:35:10,431 - PoinTr - INFO - config.bnmscheduler.kwargs.bn_decay : 0.5
2021-12-17 09:35:10,432 - PoinTr - INFO - config.bnmscheduler.kwargs.bn_momentum : 0.9
2021-12-17 09:35:10,432 - PoinTr - INFO - config.bnmscheduler.kwargs.lowest_decay : 0.01
2021-12-17 09:35:10,432 - PoinTr - INFO - config.dataset = edict()
2021-12-17 09:35:10,433 - PoinTr - INFO - config.dataset.train = edict()
2021-12-17 09:35:10,433 - PoinTr - INFO - config.dataset.train._base_ = edict()
2021-12-17 09:35:10,433 - PoinTr - INFO - config.dataset.train._base_.NAME : PCN
2021-12-17 09:35:10,433 - PoinTr - INFO - config.dataset.train._base_.CATEGORY_FILE_PATH : data/PCN/PCN.json
2021-12-17 09:35:10,434 - PoinTr - INFO - config.dataset.train._base_.N_POINTS : 16384
2021-12-17 09:35:10,434 - PoinTr - INFO - config.dataset.train._base_.N_RENDERINGS : 8
2021-12-17 09:35:10,434 - PoinTr - INFO - config.dataset.train._base_.PARTIAL_POINTS_PATH : data/PCN/%s/partial/%s/%s/%02d.pcd
2021-12-17 09:35:10,435 - PoinTr - INFO - config.dataset.train._base_.COMPLETE_POINTS_PATH : data/PCN/%s/complete/%s/%s.pcd
2021-12-17 09:35:10,436 - PoinTr - INFO - config.dataset.train._base_.CARS : False
2021-12-17 09:35:10,436 - PoinTr - INFO - config.dataset.train.others = edict()
2021-12-17 09:35:10,436 - PoinTr - INFO - config.dataset.train.others.subset : train
2021-12-17 09:35:10,437 - PoinTr - INFO - config.dataset.train.others.bs : 48
2021-12-17 09:35:10,437 - PoinTr - INFO - config.dataset.val = edict()
2021-12-17 09:35:10,437 - PoinTr - INFO - config.dataset.val._base_ = edict()
2021-12-17 09:35:10,438 - PoinTr - INFO - config.dataset.val._base_.NAME : PCN
2021-12-17 09:35:10,438 - PoinTr - INFO - config.dataset.val._base_.CATEGORY_FILE_PATH : data/PCN/PCN.json
2021-12-17 09:35:10,438 - PoinTr - INFO - config.dataset.val._base_.N_POINTS : 16384
2021-12-17 09:35:10,438 - PoinTr - INFO - config.dataset.val._base_.N_RENDERINGS : 8
2021-12-17 09:35:10,439 - PoinTr - INFO - config.dataset.val._base_.PARTIAL_POINTS_PATH : data/PCN/%s/partial/%s/%s/%02d.pcd
2021-12-17 09:35:10,439 - PoinTr - INFO - config.dataset.val._base_.COMPLETE_POINTS_PATH : data/PCN/%s/complete/%s/%s.pcd
2021-12-17 09:35:10,440 - PoinTr - INFO - config.dataset.val._base_.CARS : False
2021-12-17 09:35:10,440 - PoinTr - INFO - config.dataset.val.others = edict()
2021-12-17 09:35:10,441 - PoinTr - INFO - config.dataset.val.others.subset : test
2021-12-17 09:35:10,441 - PoinTr - INFO - config.dataset.test = edict()
2021-12-17 09:35:10,441 - PoinTr - INFO - config.dataset.test._base_ = edict()
2021-12-17 09:35:10,442 - PoinTr - INFO - config.dataset.test._base_.NAME : PCN
2021-12-17 09:35:10,442 - PoinTr - INFO - config.dataset.test._base_.CATEGORY_FILE_PATH : data/PCN/PCN.json
2021-12-17 09:35:10,442 - PoinTr - INFO - config.dataset.test._base_.N_POINTS : 16384
2021-12-17 09:35:10,442 - PoinTr - INFO - config.dataset.test._base_.N_RENDERINGS : 8
2021-12-17 09:35:10,445 - PoinTr - INFO - config.dataset.test._base_.PARTIAL_POINTS_PATH : data/PCN/%s/partial/%s/%s/%02d.pcd
2021-12-17 09:35:10,445 - PoinTr - INFO - config.dataset.test._base_.COMPLETE_POINTS_PATH : data/PCN/%s/complete/%s/%s.pcd
2021-12-17 09:35:10,446 - PoinTr - INFO - config.dataset.test._base_.CARS : False
2021-12-17 09:35:10,446 - PoinTr - INFO - config.dataset.test.others = edict()
2021-12-17 09:35:10,447 - PoinTr - INFO - config.dataset.test.others.subset : test
2021-12-17 09:35:10,447 - PoinTr - INFO - config.model = edict()
2021-12-17 09:35:10,447 - PoinTr - INFO - config.model.NAME : PoinTr
2021-12-17 09:35:10,447 - PoinTr - INFO - config.model.num_pred : 14336
2021-12-17 09:35:10,448 - PoinTr - INFO - config.model.num_query : 224
2021-12-17 09:35:10,448 - PoinTr - INFO - config.model.knn_layer : 1
2021-12-17 09:35:10,448 - PoinTr - INFO - config.model.trans_dim : 384
2021-12-17 09:35:10,449 - PoinTr - INFO - config.total_bs : 48
2021-12-17 09:35:10,449 - PoinTr - INFO - config.step_per_update : 1
2021-12-17 09:35:10,449 - PoinTr - INFO - config.max_epoch : 300
2021-12-17 09:35:10,450 - PoinTr - INFO - config.consider_metric : CDL1
2021-12-17 09:35:10,450 - PoinTr - INFO - Distributed training: False
2021-12-17 09:35:10,450 - PoinTr - INFO - Set random seed to 0, deterministic: False
2021-12-17 09:35:10,451 - PoinTr - INFO - Tester start ...
2021-12-17 09:35:10,460 - PCNDATASET - INFO - Collecting files of Taxonomy [ID=02691156, Name=airplane]
2021-12-17 09:35:10,461 - PCNDATASET - INFO - Collecting files of Taxonomy [ID=02933112, Name=cabinet]
2021-12-17 09:35:10,461 - PCNDATASET - INFO - Collecting files of Taxonomy [ID=02958343, Name=car]
2021-12-17 09:35:10,462 - PCNDATASET - INFO - Collecting files of Taxonomy [ID=03001627, Name=chair]
2021-12-17 09:35:10,463 - PCNDATASET - INFO - Collecting files of Taxonomy [ID=03636649, Name=lamp]
2021-12-17 09:35:10,463 - PCNDATASET - INFO - Collecting files of Taxonomy [ID=04256520, Name=sofa]
2021-12-17 09:35:10,464 - PCNDATASET - INFO - Collecting files of Taxonomy [ID=04379243, Name=table]
2021-12-17 09:35:10,464 - PCNDATASET - INFO - Collecting files of Taxonomy [ID=04530566, Name=watercraft]
2021-12-17 09:35:10,465 - PCNDATASET - INFO - Complete collecting files of the dataset. Total files: 1200
2021-12-17 09:35:10,466 - MODEL - INFO -  Transformer with knn_layer 1
2021-12-17 09:35:11,071 - PoinTr - INFO - Loading weights from ./pretrained/PoinTr_PCN.pth...
2021-12-17 09:35:12,220 - PoinTr - INFO - ckpts @ 289 epoch( performance = No Metrics)
C:\Users\peter\AppData\Local\Programs\Python\Python36\lib\site-packages\torchvision\io\image.py:11: UserWarning: Failed to load image Python extension: [WinError 126] Le module spécifié est introuvable
  warn(f"Failed to load image Python extension: {e}")
C:\Users\peter\AppData\Local\Programs\Python\Python36\lib\site-packages\torchvision\io\image.py:11: UserWarning: Failed to load image Python extension: [WinError 126] Le module spécifié est introuvable
  warn(f"Failed to load image Python extension: {e}")
C:\Users\peter\AppData\Local\Programs\Python\Python36\lib\site-packages\torchvision\io\image.py:11: UserWarning: Failed to load image Python extension: [WinError 126] Le module spécifié est introuvable
  warn(f"Failed to load image Python extension: {e}")
C:\Users\peter\AppData\Local\Programs\Python\Python36\lib\site-packages\torchvision\io\image.py:11: UserWarning: Failed to load image Python extension: [WinError 126] Le module spécifié est introuvable
  warn(f"Failed to load image Python extension: {e}")
[Open3D WARNING] Read PCD failed: unable to open file: data/PCN/test/partial/02691156/bb9ba5deec9e2a5fca8607f540cc62ba/00.pcd
[Open3D WARNING] Read PCD failed: unable to open file: data/PCN/test/partial/02691156/2c16ac865f06542381598514fe928082/00.pcd[Open3D WARNING]
Read PCD failed: unable to open file: data/PCN/test/partial/02691156/e431f79ac9f0266bca677733d59db4df/00.pcd
[Open3D WARNING] [Open3D WARNING] Read PCD failed: unable to open file: data/PCN/test/complete/02691156/e431f79ac9f0266bca677733d59db4df.pcd
[Open3D WARNING] Read PCD failed: unable to open file: data/PCN/test/complete/02691156/2c16ac865f06542381598514fe928082.pcdRead PCD failed: unable to open file: data/PCN/test/complete/02691156/bb9ba5deec9e2a5fca8607f540cc62ba.pcd

[Open3D WARNING] Read PCD failed: unable to open file: data/PCN/test/partial/02691156/c510e14ac20edee814a46d7ec44fc258/00.pcd
[Open3D WARNING] [Open3D WARNING] Read PCD failed: unable to open file: data/PCN/test/partial/02691156/ec879d7360572a5db65bd29086fc2a67/00.pcdRead PCD failed: unable to open file: data/PCN/test/partial/02691156/3c6c4be95d2dad2937b25178f5
4477f4/00.pcd

Traceback (most recent call last):
[Open3D WARNING] Read PCD failed: unable to open file: data/PCN/test/complete/02691156/c510e14ac20edee814a46d7ec44fc258.pcd  File "main.py", line 68, in <module>

[Open3D WARNING] Read PCD failed: unable to open file: data/PCN/test/complete/02691156/3c6c4be95d2dad2937b25178f54477f4.pcd
[Open3D WARNING]     Read PCD failed: unable to open file: data/PCN/test/complete/02691156/ec879d7360572a5db65bd29086fc2a67.pcdmain()

  File "main.py", line 62, in main
    test_net(args, config)
[Open3D WARNING] Read PCD failed: unable to open file: data/PCN/test/partial/02691156/2a05d684eeb9c1cfae2ca9bb680dd18b/00.pcd
  File "C:\Repos\PoinTr-master\tools\runner.py", line 304, in test_net
[Open3D WARNING] [Open3D WARNING] Read PCD failed: unable to open file: data/PCN/test/complete/02691156/2a05d684eeb9c1cfae2ca9bb680dd18b.pcd
Read PCD failed: unable to open file: data/PCN/test/partial/02691156/604392af2cbb7d1fe30ec10233e7931a/00.pcd
    test(base_model, test_dataloader, ChamferDisL1, ChamferDisL2, args, config, logger=logger)[Open3D WARNING] Read PCD failed: unable to open file: data/PCN/test/complete/02691156/604392af2cbb7d1fe30ec10233e7931a.pcd

  File "C:\Repos\PoinTr-master\tools\runner.py", line 316, in test
    for idx, (taxonomy_ids, model_ids, data) in enumerate(test_dataloader):
  File "C:\Users\peter\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\utils\data\dataloader.py", line 521, in __next__
[Open3D WARNING] Read PCD failed: unable to open file: data/PCN/test/partial/02691156/21c7cc3e5f27540be6553f96496649c9/00.pcd
[Open3D WARNING] Read PCD failed: unable to open file: data/PCN/test/complete/02691156/21c7cc3e5f27540be6553f96496649c9.pcd
    data = self._next_data()
  File "C:\Users\peter\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\utils\data\dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "C:\Users\peter\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\utils\data\dataloader.py", line 1229, in _process_data
    data.reraise()
  File "C:\Users\peter\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\_utils.py", line 434, in reraise
    raise exception
AssertionError: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Users\peter\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\utils\data\_utils\worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\peter\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\peter\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Repos\PoinTr-master\datasets\PCNDataset.py", line 103, in __getitem__
    assert data['gt'].shape[0] == self.npoints
AssertionError`

The error seems to come from Open3D but I have no idea how to fix it.

**Comment by blukaz** [comment]
Hi @LeiKeRrr ,

`C:\Users\peter\AppData\Local\Programs\Python\Python36\lib\site-packages\torchvision\io\image.py:11: UserWarning: Failed
to load image Python extension: [WinError 126] Le module spécifié est introuvable` → this means that something is wrong with your environment and it can't find torch... try to make some minimal examples in the python console to make sure your environment is set and ready to use

the other issues related to Open3D means most probably that your path to the file is incorrect / the file is not there... try to load those files in python console using open3D just to see everything is fine.

Let me know once you've checked the proposed solutions

**Comment by LeiKeRrr** [comment]
Hi @blukaz !

I'm sorry for the long absence.

Thanks to your advice I was able to solve the problems. Here is what I get for the evaluation: 

![image](https://user-images.githubusercontent.com/88313194/157635779-e79c0cbc-a26b-4ec9-ad87-4d4921f6b53b.png)

Should a viewing window open? Because I managed to fix the problem of the python extension but another error appeared: the cp command is not recognized... 

Also, could you tell me how to run the PoinTr program on my own files ? 

Thanks

**Comment by blukaz** [comment]
Hi @LeiKeRrr ,

Could you give more details regarding the first issue?
In order to train PoinTr on custom data you have to write your dataloader. For that you can follow simply the Shapenet dataset script for example. One important thing is that your point cloud data has to be normalized

**Comment by LeiKeRrr** [comment]
Hi @blukaz !

Thank you for your answer. 

This is the error I get when running the command : 

```
pierrot@DESKTOP-FMMUKS2:/mnt/c/Repos/PoinTr-master$ bash ./scripts/test.sh 0 \
>     --ckpts ./pretrained/PoinTr_PCN.pth \
>     --config ./cfgs/PCN_models/PoinTr.yaml \
>     --exp_name example
+ GPUS=0
+ PY_ARGS='--ckpts ./pretrained/PoinTr_PCN.pth --config ./cfgs/PCN_models/PoinTr.yaml --exp_name example'
+ CUDA_VISIBLE_DEVICES=0
+ /mnt/c/Users/peter/AppData/Local/Programs/Python/Python36/python.exe main.py --test --ckpts ./pretrained/PoinTr_PCN.pth --config ./cfgs/PCN_models/PoinTr.yaml --exp_name example
'cp' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.
2022-03-13 09:19:09,868 - PoinTr - INFO - Copy the Config file from ./cfgs/PCN_models/PoinTr.yaml to ./experiments\PoinTr\PCN_models\test_example\config.yaml
2022-03-13 09:19:09,869 - PoinTr - INFO - args.config : ./cfgs/PCN_models/PoinTr.yaml
2022-03-13 09:19:09,869 - PoinTr - INFO - args.launcher : none

```
And then there is the result of the evaluation.
