### ISSUE TITLE
multiprocessing errors

### ISSUE THREAD

**Issue by zura-false** [yuxumin/PoinTr#32]
Hi!
I got an error when training with two GPUs, and the trained model is not very good.can you give me some advice.
I ran the code “CUDA_VISIBLE_DEVICES=0,1 bash ./scripts/dist_train.sh 2 13232 --config ./cfgs/PCN_models/PoinTr.yaml --exp_name example”
and got the following error:

Traceback (most recent call last):
  File "main.py", line 68, in <module>
    main()
  File "main.py", line 64, in main
    run_net(args, config, train_writer, val_writer)
  File "/home/uer/codes/PoinTr/tools/runner.py", line 159, in run_net
    train_writer.close()
AttributeError: 'NoneType' object has no attribute 'close'

WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 13571 closing signal SIGTERM
/home/uer/anaconda3/envs/PoinTr/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 6 leaked semaphores to clean up at shutdown
  len(cache))
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 1 (pid: 13572) of binary: /home/uer/anaconda3/envs/PoinTr/bin/python
Traceback (most recent call last):
  File "/home/uer/anaconda3/envs/PoinTr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/uer/anaconda3/envs/PoinTr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/uer/anaconda3/envs/PoinTr/lib/python3.7/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/uer/anaconda3/envs/PoinTr/lib/python3.7/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/uer/anaconda3/envs/PoinTr/lib/python3.7/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/uer/anaconda3/envs/PoinTr/lib/python3.7/site-packages/torch/distributed/run.py", line 713, in run
    )(*cmd_args)
  File "/home/uer/anaconda3/envs/PoinTr/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/uer/anaconda3/envs/PoinTr/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 261, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
main.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-02-14_01:37:10
  host      :uer
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 13572)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by zura-false** [comment]
> 

thanks！I will try it.
