### ISSUE TITLE
A problem named "AssertionError"

### ISSUE THREAD

**Issue by Jimmybear-123** [yuxumin/PoinTr#36]
Hi, sorry to bother you. I got another problem when I run
  `bash ./scripts/test.sh 0 \
>     --ckpts ./pretrained/PoinTr_PCN.pth \
>     --config ./cfgs/PCN_models/PoinTr.yaml \
>     --exp_name example
`
The Terminal shows
`+ GPUS=0
+ PY_ARGS='--ckpts ./pretrained/PoinTr_PCN.pth --config ./cfgs/PCN_models/PoinTr.yaml --exp_name example'
+ CUDA_VISIBLE_DEVICES=0
+ python main.py --test --ckpts ./pretrained/PoinTr_PCN.pth --config ./cfgs/PCN_models/PoinTr.yaml --exp_name example
/home/jimmy/anaconda3/lib/python3.9/site-packages/pointnet2_ops/pointnet2_utils.py:15: UserWarning: Unable to load pointnet2_ops cpp extension. JIT Compiling.
  warnings.warn("Unable to load pointnet2_ops cpp extension. JIT Compiling.")
2022-03-14 13:51:16,679 - PoinTr - INFO - Copy the Config file from ./cfgs/PCN_models/PoinTr.yaml to ./experiments/PoinTr/PCN_models/test_example/config.yaml
2022-03-14 13:51:16,679 - PoinTr - INFO - args.config : ./cfgs/PCN_models/PoinTr.yaml
2022-03-14 13:51:16,680 - PoinTr - INFO - args.launcher : none
2022-03-14 13:51:16,680 - PoinTr - INFO - args.local_rank : 0
2022-03-14 13:51:16,680 - PoinTr - INFO - args.num_workers : 4
2022-03-14 13:51:16,680 - PoinTr - INFO - args.seed : 0
2022-03-14 13:51:16,680 - PoinTr - INFO - args.deterministic : False
2022-03-14 13:51:16,680 - PoinTr - INFO - args.sync_bn : False
2022-03-14 13:51:16,680 - PoinTr - INFO - args.exp_name : test_example
2022-03-14 13:51:16,680 - PoinTr - INFO - args.start_ckpts : None
2022-03-14 13:51:16,680 - PoinTr - INFO - args.ckpts : ./pretrained/PoinTr_PCN.pth
2022-03-14 13:51:16,680 - PoinTr - INFO - args.val_freq : 1
2022-03-14 13:51:16,680 - PoinTr - INFO - args.resume : False
2022-03-14 13:51:16,680 - PoinTr - INFO - args.test : True
2022-03-14 13:51:16,680 - PoinTr - INFO - args.mode : None
2022-03-14 13:51:16,680 - PoinTr - INFO - args.experiment_path : ./experiments/PoinTr/PCN_models/test_example
2022-03-14 13:51:16,680 - PoinTr - INFO - args.tfboard_path : ./experiments/PoinTr/PCN_models/TFBoard/test_example
2022-03-14 13:51:16,680 - PoinTr - INFO - args.log_name : PoinTr
2022-03-14 13:51:16,680 - PoinTr - INFO - args.use_gpu : True
2022-03-14 13:51:16,680 - PoinTr - INFO - args.distributed : False
2022-03-14 13:51:16,680 - PoinTr - INFO - config.optimizer = edict()
2022-03-14 13:51:16,680 - PoinTr - INFO - config.optimizer.type : AdamW
2022-03-14 13:51:16,680 - PoinTr - INFO - config.optimizer.kwargs = edict()
2022-03-14 13:51:16,680 - PoinTr - INFO - config.optimizer.kwargs.lr : 0.0005
2022-03-14 13:51:16,680 - PoinTr - INFO - config.optimizer.kwargs.weight_decay : 0.0005
2022-03-14 13:51:16,680 - PoinTr - INFO - config.scheduler = edict()
2022-03-14 13:51:16,680 - PoinTr - INFO - config.scheduler.type : LambdaLR
2022-03-14 13:51:16,681 - PoinTr - INFO - config.scheduler.kwargs = edict()
2022-03-14 13:51:16,681 - PoinTr - INFO - config.scheduler.kwargs.decay_step : 21
2022-03-14 13:51:16,681 - PoinTr - INFO - config.scheduler.kwargs.lr_decay : 0.9
2022-03-14 13:51:16,681 - PoinTr - INFO - config.scheduler.kwargs.lowest_decay : 0.02
2022-03-14 13:51:16,681 - PoinTr - INFO - config.bnmscheduler = edict()
2022-03-14 13:51:16,681 - PoinTr - INFO - config.bnmscheduler.type : Lambda
2022-03-14 13:51:16,681 - PoinTr - INFO - config.bnmscheduler.kwargs = edict()
2022-03-14 13:51:16,681 - PoinTr - INFO - config.bnmscheduler.kwargs.decay_step : 21
2022-03-14 13:51:16,681 - PoinTr - INFO - config.bnmscheduler.kwargs.bn_decay : 0.5
2022-03-14 13:51:16,681 - PoinTr - INFO - config.bnmscheduler.kwargs.bn_momentum : 0.9
2022-03-14 13:51:16,681 - PoinTr - INFO - config.bnmscheduler.kwargs.lowest_decay : 0.01
2022-03-14 13:51:16,681 - PoinTr - INFO - config.dataset = edict()
2022-03-14 13:51:16,681 - PoinTr - INFO - config.dataset.train = edict()
2022-03-14 13:51:16,681 - PoinTr - INFO - config.dataset.train._base_ = edict()
2022-03-14 13:51:16,681 - PoinTr - INFO - config.dataset.train._base_.NAME : PCN
2022-03-14 13:51:16,681 - PoinTr - INFO - config.dataset.train._base_.CATEGORY_FILE_PATH : data/PCN/PCN.json
2022-03-14 13:51:16,681 - PoinTr - INFO - config.dataset.train._base_.N_POINTS : 16384
2022-03-14 13:51:16,681 - PoinTr - INFO - config.dataset.train._base_.N_RENDERINGS : 8
2022-03-14 13:51:16,681 - PoinTr - INFO - config.dataset.train._base_.PARTIAL_POINTS_PATH : data/PCN/%s/partial/%s/%s/%02d.pcd
2022-03-14 13:51:16,681 - PoinTr - INFO - config.dataset.train._base_.COMPLETE_POINTS_PATH : data/PCN/%s/complete/%s/%s.pcd
2022-03-14 13:51:16,681 - PoinTr - INFO - config.dataset.train._base_.CARS : False
2022-03-14 13:51:16,681 - PoinTr - INFO - config.dataset.train.others = edict()
2022-03-14 13:51:16,681 - PoinTr - INFO - config.dataset.train.others.subset : train
2022-03-14 13:51:16,681 - PoinTr - INFO - config.dataset.train.others.bs : 48
2022-03-14 13:51:16,681 - PoinTr - INFO - config.dataset.val = edict()
2022-03-14 13:51:16,681 - PoinTr - INFO - config.dataset.val._base_ = edict()
2022-03-14 13:51:16,681 - PoinTr - INFO - config.dataset.val._base_.NAME : PCN
2022-03-14 13:51:16,681 - PoinTr - INFO - config.dataset.val._base_.CATEGORY_FILE_PATH : data/PCN/PCN.json
2022-03-14 13:51:16,682 - PoinTr - INFO - config.dataset.val._base_.N_POINTS : 16384
2022-03-14 13:51:16,682 - PoinTr - INFO - config.dataset.val._base_.N_RENDERINGS : 8
2022-03-14 13:51:16,682 - PoinTr - INFO - config.dataset.val._base_.PARTIAL_POINTS_PATH : data/PCN/%s/partial/%s/%s/%02d.pcd
2022-03-14 13:51:16,682 - PoinTr - INFO - config.dataset.val._base_.COMPLETE_POINTS_PATH : data/PCN/%s/complete/%s/%s.pcd
2022-03-14 13:51:16,682 - PoinTr - INFO - config.dataset.val._base_.CARS : False
2022-03-14 13:51:16,682 - PoinTr - INFO - config.dataset.val.others = edict()
2022-03-14 13:51:16,682 - PoinTr - INFO - config.dataset.val.others.subset : test
2022-03-14 13:51:16,682 - PoinTr - INFO - config.dataset.test = edict()
2022-03-14 13:51:16,682 - PoinTr - INFO - config.dataset.test._base_ = edict()
2022-03-14 13:51:16,682 - PoinTr - INFO - config.dataset.test._base_.NAME : PCN
2022-03-14 13:51:16,682 - PoinTr - INFO - config.dataset.test._base_.CATEGORY_FILE_PATH : data/PCN/PCN.json
2022-03-14 13:51:16,682 - PoinTr - INFO - config.dataset.test._base_.N_POINTS : 16384
2022-03-14 13:51:16,682 - PoinTr - INFO - config.dataset.test._base_.N_RENDERINGS : 8
2022-03-14 13:51:16,682 - PoinTr - INFO - config.dataset.test._base_.PARTIAL_POINTS_PATH : data/PCN/%s/partial/%s/%s/%02d.pcd
2022-03-14 13:51:16,682 - PoinTr - INFO - config.dataset.test._base_.COMPLETE_POINTS_PATH : data/PCN/%s/complete/%s/%s.pcd
2022-03-14 13:51:16,682 - PoinTr - INFO - config.dataset.test._base_.CARS : False
2022-03-14 13:51:16,682 - PoinTr - INFO - config.dataset.test.others = edict()
2022-03-14 13:51:16,682 - PoinTr - INFO - config.dataset.test.others.subset : test
2022-03-14 13:51:16,682 - PoinTr - INFO - config.model = edict()
2022-03-14 13:51:16,682 - PoinTr - INFO - config.model.NAME : PoinTr
2022-03-14 13:51:16,682 - PoinTr - INFO - config.model.num_pred : 14336
2022-03-14 13:51:16,682 - PoinTr - INFO - config.model.num_query : 224
2022-03-14 13:51:16,682 - PoinTr - INFO - config.model.knn_layer : 1
2022-03-14 13:51:16,682 - PoinTr - INFO - config.model.trans_dim : 384
2022-03-14 13:51:16,682 - PoinTr - INFO - config.total_bs : 48
2022-03-14 13:51:16,682 - PoinTr - INFO - config.step_per_update : 1
2022-03-14 13:51:16,682 - PoinTr - INFO - config.max_epoch : 300
2022-03-14 13:51:16,682 - PoinTr - INFO - config.consider_metric : CDL1
2022-03-14 13:51:16,682 - PoinTr - INFO - Distributed training: False
2022-03-14 13:51:16,683 - PoinTr - INFO - Set random seed to 0, deterministic: False
2022-03-14 13:51:16,683 - PoinTr - INFO - Tester start ... 
2022-03-14 13:51:16,688 - PCNDATASET - INFO - Collecting files of Taxonomy [ID=02691156, Name=airplane]
2022-03-14 13:51:16,688 - PCNDATASET - INFO - Collecting files of Taxonomy [ID=02933112, Name=cabinet]
2022-03-14 13:51:16,689 - PCNDATASET - INFO - Collecting files of Taxonomy [ID=02958343, Name=car]
2022-03-14 13:51:16,689 - PCNDATASET - INFO - Collecting files of Taxonomy [ID=03001627, Name=chair]
2022-03-14 13:51:16,689 - PCNDATASET - INFO - Collecting files of Taxonomy [ID=03636649, Name=lamp]
2022-03-14 13:51:16,689 - PCNDATASET - INFO - Collecting files of Taxonomy [ID=04256520, Name=sofa]
2022-03-14 13:51:16,689 - PCNDATASET - INFO - Collecting files of Taxonomy [ID=04379243, Name=table]
2022-03-14 13:51:16,689 - PCNDATASET - INFO - Collecting files of Taxonomy [ID=04530566, Name=watercraft]
2022-03-14 13:51:16,690 - PCNDATASET - INFO - Complete collecting files of the dataset. Total files: 1200
2022-03-14 13:51:16,690 - MODEL - INFO -  Transformer with knn_layer 1
2022-03-14 13:51:19,295 - PoinTr - INFO - Loading weights from ./pretrained/PoinTr_PCN.pth...
2022-03-14 13:51:19,496 - PoinTr - INFO - ckpts @ 291 epoch( performance = {'F-Score': 0.7966486847844346, 'CDL1': 7.263054704332413, 'CDL2': 0.2274231300179963})
[Open3D WARNING] Read PCD failed: unable to open file: data/PCN/test/partial/02691156/bb9ba5deec9e2a5fca8607f540cc62ba/00.pcd
[Open3D WARNING] Read PCD failed: unable to open file: data/PCN/test/complete/02691156/bb9ba5deec9e2a5fca8607f540cc62ba.pcd
[Open3D WARNING] Read PCD failed: unable to open file: data/PCN/test/partial/02691156/c510e14ac20edee814a46d7ec44fc258/00.pcd
[Open3D WARNING] Read PCD failed: unable to open file: data/PCN/test/partial/02691156/e431f79ac9f0266bca677733d59db4df/00.pcd
[Open3D WARNING] Read PCD failed: unable to open file: data/PCN/test/complete/02691156/c510e14ac20edee814a46d7ec44fc258.pcd
[Open3D WARNING] Read PCD failed: unable to open file: data/PCN/test/complete/02691156/e431f79ac9f0266bca677733d59db4df.pcd
[Open3D WARNING] Read PCD failed: unable to open file: data/PCN/test/partial/02691156/2a05d684eeb9c1cfae2ca9bb680dd18b/00.pcd
[Open3D WARNING] Read PCD failed: unable to open file: data/PCN/test/partial/02691156/2c16ac865f06542381598514fe928082/00.pcd
[Open3D WARNING] Read PCD failed: unable to open file: data/PCN/test/complete/02691156/2c16ac865f06542381598514fe928082.pcd
[Open3D WARNING] Read PCD failed: unable to open file: data/PCN/test/complete/02691156/2a05d684eeb9c1cfae2ca9bb680dd18b.pcd
[Open3D WARNING] Read PCD failed: unable to open file: data/PCN/test/partial/02691156/ec879d7360572a5db65bd29086fc2a67/00.pcd
[Open3D WARNING] Read PCD failed: unable to open file: data/PCN/test/complete/02691156/ec879d7360572a5db65bd29086fc2a67.pcd
[Open3D WARNING] Read PCD failed: unable to open file: data/PCN/test/partial/02691156/604392af2cbb7d1fe30ec10233e7931a/00.pcd
[Open3D WARNING] Read PCD failed: unable to open file: data/PCN/test/partial/02691156/3c6c4be95d2dad2937b25178f54477f4/00.pcd
[Open3D WARNING] Read PCD failed: unable to open file: data/PCN/test/complete/02691156/604392af2cbb7d1fe30ec10233e7931a.pcd
Traceback (most recent call last):
  File "/home/jimmy/PointCloudProduct/PoinTr-master/main.py", line 68, in <module>
[Open3D WARNING] Read PCD failed: unable to open file: data/PCN/test/complete/02691156/3c6c4be95d2dad2937b25178f54477f4.pcd
[Open3D WARNING] Read PCD failed: unable to open file: data/PCN/test/partial/02691156/21c7cc3e5f27540be6553f96496649c9/00.pcd
[Open3D WARNING] Read PCD failed: unable to open file: data/PCN/test/complete/02691156/21c7cc3e5f27540be6553f96496649c9.pcd
    main()
  File "/home/jimmy/PointCloudProduct/PoinTr-master/main.py", line 62, in main
    test_net(args, config)
  File "/home/jimmy/PointCloudProduct/PoinTr-master/tools/runner.py", line 304, in test_net
    test(base_model, test_dataloader, ChamferDisL1, ChamferDisL2, args, config, logger=logger)
  File "/home/jimmy/PointCloudProduct/PoinTr-master/tools/runner.py", line 316, in test
    for idx, (taxonomy_ids, model_ids, data) in enumerate(test_dataloader):
  File "/home/jimmy/anaconda3/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/home/jimmy/anaconda3/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1199, in _next_data
    return self._process_data(data)
  File "/home/jimmy/anaconda3/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
    data.reraise()
  File "/home/jimmy/anaconda3/lib/python3.9/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
AssertionError: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/jimmy/anaconda3/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/jimmy/anaconda3/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/jimmy/anaconda3/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/jimmy/PointCloudProduct/PoinTr-master/datasets/PCNDataset.py", line 103, in __getitem__
    assert data['gt'].shape[0] == self.npoints
AssertionError
`
I have checked my pytorch, and it is running well. Is that something wrong in open3d?

**Comment by yuxumin** [comment]
Can you check the file at path `data/PCN/test/partial/02691156/c510e14ac20edee814a46d7ec44fc258/00.pcd`?

**Comment by yuxumin** [comment]
Close it since no response. Feel free to re-open it if problems still exist
