### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by zztzzt200** [yuxumin/PoinTr#40]
I used the pretrained model of PCN to test on PCN and got some issue:
```
Traceback (most recent call last):
  File "main.py", line 68, in <module>
    main()
  File "main.py", line 62, in main
    test_net(args, config)
  File "/media/zt/KINGSTON/PoinTr-master/tools/runner.py", line 304, in test_net
    test(base_model, test_dataloader, ChamferDisL1, ChamferDisL2, args, config, logger=logger)
  File "/media/zt/KINGSTON/PoinTr-master/tools/runner.py", line 330, in test
    sparse_loss_l1 =  ChamferDisL1(coarse_points, gt)
  File "/home/zt/anaconda3/envs/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/media/zt/KINGSTON/PoinTr-master/extensions/chamfer_dist/__init__.py", line 79, in forward
    dist1, dist2 = ChamferFunction.apply(xyz1, xyz2)
  File "/media/zt/KINGSTON/PoinTr-master/extensions/chamfer_dist/__init__.py", line 16, in forward
    dist1, dist2, idx1, idx2 = chamfer.forward(xyz1, xyz2)
TypeError: forward(): incompatible function arguments. The following argument types are supported:
    1. (arg0: at::Tensor, arg1: at::Tensor, arg2: at::Tensor, arg3: at::Tensor, arg4: at::Tensor, arg5: at::Tensor) -> int

Invoked with: tensor([[[ 0.3372, -0.0633,  0.0071],
         [-0.3084, -0.0587, -0.0534],
         [ 0.1694, -0.0381,  0.0665],
         ...,
         [ 0.0708, -0.0256,  0.0818],
         [-0.2394,  0.0460,  0.0049],
         [-0.0334, -0.1057, -0.0396]]], device='cuda:0'), tensor([[[-0.0469, -0.0480,  0.1070],
         [-0.2379, -0.0410,  0.0122],
         [ 0.0307, -0.0627,  0.0817],
         ...,
         [ 0.0234, -0.0052,  0.0366],
         [-0.1879, -0.0876, -0.0684],
         [-0.0315, -0.0052, -0.0005]]], device='cuda:0')

```

**Comment by yuxumin** [comment]
Hi,  I can not figure out the cause of the problem with what you show in this issue. can you inference the model on other benchmark or train a model with the code?

**Comment by zztzzt200** [comment]
Well, I'll try it, thank you

**Comment by yuxumin** [comment]
Close it since no response. Feel free to re-open it if problems still exist
