### ISSUE TITLE
Which configuration parameter to change for saving memory?

### ISSUE THREAD

**Issue by Takenokono** [yuxumin/PoinTr#42]
Hi! Thank you for amazing your work. I was so impressed.

I've tried to train this network with own my point cloud data based on the PCN dataset.
But I conflicted memory problem.

Could you tell me which parameter to tweak in the settings?

Error message below...

```
+ GPUS=0
+ PY_ARGS='--config ./cfgs/PCN_models/PoinTr.yaml --exp_name example'
+ CUDA_VISIBLE_DEVICES=0
+ python main.py --config ./cfgs/PCN_models/PoinTr.yaml --exp_name example
2022-04-12 15:27:15,511 - PoinTr - INFO - Copy the Config file from ./cfgs/PCN_models/PoinTr.yaml to ./experiments/PoinTr/PCN_models/example/config.yaml
2022-04-12 15:27:15,511 - PoinTr - INFO - args.config : ./cfgs/PCN_models/PoinTr.yaml
2022-04-12 15:27:15,511 - PoinTr - INFO - args.launcher : none
2022-04-12 15:27:15,511 - PoinTr - INFO - args.local_rank : 0
2022-04-12 15:27:15,511 - PoinTr - INFO - args.num_workers : 4
2022-04-12 15:27:15,511 - PoinTr - INFO - args.seed : 0
2022-04-12 15:27:15,511 - PoinTr - INFO - args.deterministic : False
2022-04-12 15:27:15,511 - PoinTr - INFO - args.sync_bn : False
2022-04-12 15:27:15,511 - PoinTr - INFO - args.exp_name : example
2022-04-12 15:27:15,511 - PoinTr - INFO - args.start_ckpts : None
2022-04-12 15:27:15,511 - PoinTr - INFO - args.ckpts : None
2022-04-12 15:27:15,511 - PoinTr - INFO - args.val_freq : 1
2022-04-12 15:27:15,511 - PoinTr - INFO - args.resume : False
2022-04-12 15:27:15,511 - PoinTr - INFO - args.test : False
2022-04-12 15:27:15,511 - PoinTr - INFO - args.mode : None
2022-04-12 15:27:15,511 - PoinTr - INFO - args.experiment_path : ./experiments/PoinTr/PCN_models/example
2022-04-12 15:27:15,511 - PoinTr - INFO - args.tfboard_path : ./experiments/PoinTr/PCN_models/TFBoard/example
2022-04-12 15:27:15,511 - PoinTr - INFO - args.log_name : PoinTr
2022-04-12 15:27:15,511 - PoinTr - INFO - args.use_gpu : True
2022-04-12 15:27:15,512 - PoinTr - INFO - args.distributed : False
2022-04-12 15:27:15,512 - PoinTr - INFO - config.optimizer = edict()
2022-04-12 15:27:15,512 - PoinTr - INFO - config.optimizer.type : AdamW
2022-04-12 15:27:15,512 - PoinTr - INFO - config.optimizer.kwargs = edict()
2022-04-12 15:27:15,512 - PoinTr - INFO - config.optimizer.kwargs.lr : 0.0005
2022-04-12 15:27:15,512 - PoinTr - INFO - config.optimizer.kwargs.weight_decay : 0.0005
2022-04-12 15:27:15,512 - PoinTr - INFO - config.scheduler = edict()
2022-04-12 15:27:15,512 - PoinTr - INFO - config.scheduler.type : LambdaLR
2022-04-12 15:27:15,512 - PoinTr - INFO - config.scheduler.kwargs = edict()
2022-04-12 15:27:15,512 - PoinTr - INFO - config.scheduler.kwargs.decay_step : 21
2022-04-12 15:27:15,512 - PoinTr - INFO - config.scheduler.kwargs.lr_decay : 0.9
2022-04-12 15:27:15,512 - PoinTr - INFO - config.scheduler.kwargs.lowest_decay : 0.02
2022-04-12 15:27:15,512 - PoinTr - INFO - config.bnmscheduler = edict()
2022-04-12 15:27:15,512 - PoinTr - INFO - config.bnmscheduler.type : Lambda
2022-04-12 15:27:15,512 - PoinTr - INFO - config.bnmscheduler.kwargs = edict()
2022-04-12 15:27:15,512 - PoinTr - INFO - config.bnmscheduler.kwargs.decay_step : 21
2022-04-12 15:27:15,512 - PoinTr - INFO - config.bnmscheduler.kwargs.bn_decay : 0.5
2022-04-12 15:27:15,512 - PoinTr - INFO - config.bnmscheduler.kwargs.bn_momentum : 0.9
2022-04-12 15:27:15,512 - PoinTr - INFO - config.bnmscheduler.kwargs.lowest_decay : 0.01
2022-04-12 15:27:15,512 - PoinTr - INFO - config.dataset = edict()
2022-04-12 15:27:15,512 - PoinTr - INFO - config.dataset.train = edict()
2022-04-12 15:27:15,513 - PoinTr - INFO - config.dataset.train._base_ = edict()
2022-04-12 15:27:15,513 - PoinTr - INFO - config.dataset.train._base_.NAME : PCN
2022-04-12 15:27:15,513 - PoinTr - INFO - config.dataset.train._base_.CATEGORY_FILE_PATH : data/PCN/PCN.json
2022-04-12 15:27:15,513 - PoinTr - INFO - config.dataset.train._base_.N_POINTS : 16384
2022-04-12 15:27:15,513 - PoinTr - INFO - config.dataset.train._base_.N_RENDERINGS : 8
2022-04-12 15:27:15,513 - PoinTr - INFO - config.dataset.train._base_.PARTIAL_POINTS_PATH : data/PCN/%s/partial/%s/%s/%02d.pcd
2022-04-12 15:27:15,513 - PoinTr - INFO - config.dataset.train._base_.COMPLETE_POINTS_PATH : data/PCN/%s/complete/%s/%s.pcd
2022-04-12 15:27:15,513 - PoinTr - INFO - config.dataset.train._base_.CARS : False
2022-04-12 15:27:15,513 - PoinTr - INFO - config.dataset.train.others = edict()
2022-04-12 15:27:15,513 - PoinTr - INFO - config.dataset.train.others.subset : train
2022-04-12 15:27:15,513 - PoinTr - INFO - config.dataset.train.others.bs : 48
2022-04-12 15:27:15,513 - PoinTr - INFO - config.dataset.val = edict()
2022-04-12 15:27:15,513 - PoinTr - INFO - config.dataset.val._base_ = edict()
2022-04-12 15:27:15,513 - PoinTr - INFO - config.dataset.val._base_.NAME : PCN
2022-04-12 15:27:15,513 - PoinTr - INFO - config.dataset.val._base_.CATEGORY_FILE_PATH : data/PCN/PCN.json
2022-04-12 15:27:15,513 - PoinTr - INFO - config.dataset.val._base_.N_POINTS : 16384
2022-04-12 15:27:15,513 - PoinTr - INFO - config.dataset.val._base_.N_RENDERINGS : 8
2022-04-12 15:27:15,513 - PoinTr - INFO - config.dataset.val._base_.PARTIAL_POINTS_PATH : data/PCN/%s/partial/%s/%s/%02d.pcd
2022-04-12 15:27:15,513 - PoinTr - INFO - config.dataset.val._base_.COMPLETE_POINTS_PATH : data/PCN/%s/complete/%s/%s.pcd
2022-04-12 15:27:15,513 - PoinTr - INFO - config.dataset.val._base_.CARS : False
2022-04-12 15:27:15,513 - PoinTr - INFO - config.dataset.val.others = edict()
2022-04-12 15:27:15,514 - PoinTr - INFO - config.dataset.val.others.subset : test
2022-04-12 15:27:15,514 - PoinTr - INFO - config.dataset.test = edict()
2022-04-12 15:27:15,514 - PoinTr - INFO - config.dataset.test._base_ = edict()
2022-04-12 15:27:15,514 - PoinTr - INFO - config.dataset.test._base_.NAME : PCN
2022-04-12 15:27:15,514 - PoinTr - INFO - config.dataset.test._base_.CATEGORY_FILE_PATH : data/PCN/PCN.json
2022-04-12 15:27:15,514 - PoinTr - INFO - config.dataset.test._base_.N_POINTS : 16384
2022-04-12 15:27:15,514 - PoinTr - INFO - config.dataset.test._base_.N_RENDERINGS : 8
2022-04-12 15:27:15,514 - PoinTr - INFO - config.dataset.test._base_.PARTIAL_POINTS_PATH : data/PCN/%s/partial/%s/%s/%02d.pcd
2022-04-12 15:27:15,514 - PoinTr - INFO - config.dataset.test._base_.COMPLETE_POINTS_PATH : data/PCN/%s/complete/%s/%s.pcd
2022-04-12 15:27:15,514 - PoinTr - INFO - config.dataset.test._base_.CARS : False
2022-04-12 15:27:15,514 - PoinTr - INFO - config.dataset.test.others = edict()
2022-04-12 15:27:15,514 - PoinTr - INFO - config.dataset.test.others.subset : test
2022-04-12 15:27:15,514 - PoinTr - INFO - config.model = edict()
2022-04-12 15:27:15,514 - PoinTr - INFO - config.model.NAME : PoinTr
2022-04-12 15:27:15,514 - PoinTr - INFO - config.model.num_pred : 14336
2022-04-12 15:27:15,514 - PoinTr - INFO - config.model.num_query : 224
2022-04-12 15:27:15,515 - PoinTr - INFO - config.model.knn_layer : 1
2022-04-12 15:27:15,515 - PoinTr - INFO - config.model.trans_dim : 384
2022-04-12 15:27:15,515 - PoinTr - INFO - config.total_bs : 48
2022-04-12 15:27:15,515 - PoinTr - INFO - config.step_per_update : 1
2022-04-12 15:27:15,515 - PoinTr - INFO - config.max_epoch : 300
2022-04-12 15:27:15,515 - PoinTr - INFO - config.consider_metric : CDL1
2022-04-12 15:27:15,515 - PoinTr - INFO - Distributed training: False
2022-04-12 15:27:15,515 - PoinTr - INFO - Set random seed to 0, deterministic: False
2022-04-12 15:27:15,520 - PCNDATASET - INFO - Collecting files of Taxonomy [ID=02691156, Name=airplane]
2022-04-12 15:27:15,540 - PCNDATASET - INFO - Collecting files of Taxonomy [ID=02933112, Name=cabinet]
2022-04-12 15:27:15,547 - PCNDATASET - INFO - Collecting files of Taxonomy [ID=02958343, Name=car]
2022-04-12 15:27:15,573 - PCNDATASET - INFO - Collecting files of Taxonomy [ID=03001627, Name=chair]
2022-04-12 15:27:15,661 - PCNDATASET - INFO - Collecting files of Taxonomy [ID=03636649, Name=lamp]
2022-04-12 15:27:15,671 - PCNDATASET - INFO - Collecting files of Taxonomy [ID=04256520, Name=sofa]
2022-04-12 15:27:15,684 - PCNDATASET - INFO - Collecting files of Taxonomy [ID=04379243, Name=table]
2022-04-12 15:27:15,713 - PCNDATASET - INFO - Collecting files of Taxonomy [ID=04530566, Name=watercraft]
2022-04-12 15:27:15,720 - PCNDATASET - INFO - Collecting files of Taxonomy [ID=00000001, Name=house]
2022-04-12 15:27:15,721 - PCNDATASET - INFO - Complete collecting files of the dataset. Total files: 29050
2022-04-12 15:27:15,726 - PCNDATASET - INFO - Collecting files of Taxonomy [ID=02691156, Name=airplane]
2022-04-12 15:27:15,726 - PCNDATASET - INFO - Collecting files of Taxonomy [ID=02933112, Name=cabinet]
2022-04-12 15:27:15,727 - PCNDATASET - INFO - Collecting files of Taxonomy [ID=02958343, Name=car]
2022-04-12 15:27:15,727 - PCNDATASET - INFO - Collecting files of Taxonomy [ID=03001627, Name=chair]
2022-04-12 15:27:15,727 - PCNDATASET - INFO - Collecting files of Taxonomy [ID=03636649, Name=lamp]
2022-04-12 15:27:15,728 - PCNDATASET - INFO - Collecting files of Taxonomy [ID=04256520, Name=sofa]
2022-04-12 15:27:15,728 - PCNDATASET - INFO - Collecting files of Taxonomy [ID=04379243, Name=table]
2022-04-12 15:27:15,728 - PCNDATASET - INFO - Collecting files of Taxonomy [ID=04530566, Name=watercraft]
2022-04-12 15:27:15,728 - PCNDATASET - INFO - Collecting files of Taxonomy [ID=00000001, Name=house]
2022-04-12 15:27:15,728 - PCNDATASET - INFO - Complete collecting files of the dataset. Total files: 1205
2022-04-12 15:27:15,729 - MODEL - INFO -  Transformer with knn_layer 1
2022-04-12 15:27:18,763 - PoinTr - INFO - Using Data parallel ...
Traceback (most recent call last):
  File "main.py", line 68, in <module>
    main()
  File "main.py", line 64, in main
    run_net(args, config, train_writer, val_writer)
  File "/home/takenobu/デスクトップ/study/PoinTr/tools/runner.py", line 98, in run_net
    ret = base_model(partial)
  File "/home/takenobu/miniconda3/envs/torch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/takenobu/miniconda3/envs/torch/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 166, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/takenobu/miniconda3/envs/torch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/takenobu/デスクトップ/study/PoinTr/models/PoinTr.py", line 92, in forward
    q, coarse_point_cloud = self.base_model(xyz) # B M C and B M 3
  File "/home/takenobu/miniconda3/envs/torch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/takenobu/デスクトップ/study/PoinTr/models/Transformer.py", line 389, in forward
    q = blk(q, x)
  File "/home/takenobu/miniconda3/envs/torch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/takenobu/デスクトップ/study/PoinTr/models/Transformer.py", line 160, in forward
    q_1 = self.self_attn(norm_q)
  File "/home/takenobu/miniconda3/envs/torch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/takenobu/デスクトップ/study/PoinTr/models/Transformer.py", line 76, in forward
    attn = (q @ k.transpose(-2, -1)) * self.scale
RuntimeError: CUDA out of memory. Tried to allocate 56.00 MiB (GPU 0; 7.79 GiB total capacity; 5.31 GiB already allocated; 71.88 MiB free; 5.41 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

and I run below...

```
bash ./scripts/train.sh 0 --config ./cfgs/PCN_models/PoinTr.yaml --exp_name example
```

Thank you in advance!

**Comment by yuxumin** [comment]
Hi, thanks for you interest in our work!

> I've tried to train this network with own my point cloud data based on the PCN dataset.

Can you briefly introduce `your own PCN-based point cloud data`. How many points are there for a complete cloud and an incomplete cloud? Are they the same as point clouds in PCN?

Back to the problem you are facing. Have you tried training PoinTr with the original PCN dataset? From the logs you provided, I see that all configurations are the same as PCN's. Training PoinTr with "bs = 48" on the PCN dataset requires two Nvidia 2080 Ti GPUs. (but you are only using one GPU). So i think there are two solutions for you:
- Use two GPUs. `bash ./scripts/train.sh 0,1 --config ./cfgs/PCN_models/PoinTr.yaml --exp_name example`
- Reduce batch size in this line https://github.com/yuxumin/PoinTr/blob/master/cfgs/PCN_models/PoinTr.yaml#L35. (However, I do not recommend reducing the batch size)

**Comment by Takenokono** [comment]
My data only has 4096 points for the complete cloud. So as you say, I think I need to adjust a number of points for training. 

And I only have a PC with a single GPU. So I will change the batch size as the first step. And if I can, I will add a new GPU for the ideal batch size.

Thank you for dealing with it so quickly.

**Comment by yuxumin** [comment]
> 2022-04-12 15:27:15,514 - PoinTr - INFO - config.model.num_pred : 14336
> 2022-04-12 15:27:15,514 - PoinTr - INFO - config.model.num_query : 224

For the case to complete a point cloud containing 4096 points, the model is requried to predicted the missing `x` points (as inputs contains `x` points, in our code, `x = 2048`). You can try to set `num_pred ` to `2048` and `num_query ` to `128`.

**Comment by Takenokono** [comment]
Hi @yuxumin! 

Finally, it works! Thank you!
