### ISSUE TITLE
Inquiry into the generation of taxonomy id

### ISSUE THREAD

**Issue by yorklyb** [yuxumin/PoinTr#72]
@yuxumin This is an amazing work. Thanks for the release of the code!

I'm trying to merge the [CADillac dataset](https://kilthub.cmu.edu/articles/dataset/CADillac/8262593), which is composed of 1000 CAD models of cars, into the ShapeNet55. (the dataset is small so I think it might be better to merge it into ShapeNet) However, I found that in the ShapeNet55Dataset.py, taxonomy_id is required. I checked the official website of ShapeNet and I found that the model_id is given, but the taxonomy_id is not (Maybe I didn't find it).

So I'm wondering how the taxonomy_id, for instance, 02691156,  is generated? Or what is the taxonomy_id of cars?

Thanks!

**Comment by yuxumin** [comment]
hi, `taxonomy id`  is used for metric collection. The model with the same `taxonomy id` with be considered as one category. In your case, you can use a self-defined `taxonomy id`. ( Or if you want to merge the result with the car in ShapeNet55, search `taxonomy _id` for car in https://github.com/yuxumin/PoinTr/blob/master/data/shapenet_synset_dict.json)

**Comment by yorklyb** [comment]
Oh. I didn't realize that it is already given in your implementation. Thanks for your rapid reply!

**Comment by yorklyb** [comment]
Hi Xumin. I changed the names of the point cloud files to 02958343-00000x.npy. However, when I started the training, it went well in the first  200 batches. Then it complained about not finding the point cloud file. But I'm pretty sure all the npy files have been moved to 'shapenet_pc' and I also added their names to the list files in 'ShapeNet-55'. Is this due to the names of the point cloud files? Like I cannot use 00000x?
##
022-08-26 10:13:42,294 - PoinTr - INFO - Using Distributed Data parallel ...
2022-08-26 10:14:04,942 - PoinTr - INFO - [Epoch 0/200][Batch 1/446] BatchTime = 22.639 (s) DataTime = 17.450 (s) Losses = ['114.9852', '249.3642'] lr = 0.000500
2022-08-26 10:16:59,427 - PoinTr - INFO - [Epoch 0/200][Batch 101/446] BatchTime = 2.073 (s) DataTime = 0.003 (s) Losses = ['55.8735', '51.8661'] lr = 0.000500
2022-08-26 10:21:11,703 - PoinTr - INFO - [Epoch 0/200][Batch 201/446] BatchTime = 1.695 (s) DataTime = 0.002 (s) Losses = ['52.0430', '42.0736'] lr = 0.000500
Traceback (most recent call last):
  File "main.py", line 68, in <module>
    main()
  File "main.py", line 64, in main
    run_net(args, config, train_writer, val_writer)
  File "/Pointr/PoinTr/tools/runner.py", line 77, in run_net
    for idx, (taxonomy_ids, model_ids, data) in enumerate(train_dataloader):
  File "/root/anaconda3/envs/pointr/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 652, in __next__
    data = self._next_data()
  File "/root/anaconda3/envs/pointr/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1347, in _next_data
    return self._process_data(data)
  File "/root/anaconda3/envs/pointr/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1373, in _process_data
    data.reraise()
  File "/root/anaconda3/envs/pointr/lib/python3.7/site-packages/torch/_utils.py", line 461, in reraise
    raise exception
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 3.
Original Traceback (most recent call last):
  File "/root/anaconda3/envs/pointr/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/anaconda3/envs/pointr/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/anaconda3/envs/pointr/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/Pointr/PoinTr/datasets/ShapeNet55Dataset.py", line 44, in __getitem__
    data = IO.get(os.path.join(self.pc_path, sample['file_path'])).astype(np.float32)
  File "/Pointr/PoinTr/datasets/io.py", line 12, in get
    return cls._read_npy(file_path)
  File "/Pointr/PoinTr/datasets/io.py", line 25, in _read_npy
    return np.load(file_path)
  File "/root/anaconda3/envs/pointr/lib/python3.7/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'data/ShapeNet55-34/shapenet_pc/2958343-000954.npy'
