### ISSUE TITLE
Dataset issue for Shapenet Testing

### ISSUE THREAD

**Issue by matthiasjaeger95** [yuxumin/PoinTr#83]
Hello, 

when I run the Test Script for Shapenet, it does not find the files specified in the .txt
 file. I've downloaded the dataset (through the link in the readme file) and also put it in the right structure. But several files from the .txt file aren't included in the dataset. 

Is there maybe a wrong list of files or what could be the issue? 

Thank you very much. 

Below is my Error code when i run following command: 

>     --ckpts ./pretrained/PoinTr_ShapeNet55.pth \
>     --config ./cfgs/ShapeNet55_models/PoinTr.yaml \
>     --mode easy \
>     --exp_name example
+ GPUS=0
+ PY_ARGS='--ckpts ./pretrained/PoinTr_ShapeNet55.pth --config ./cfgs/ShapeNet55_models/PoinTr.yaml --mode easy --exp_name example'
+ CUDA_VISIBLE_DEVICES=0
+ python main.py --test --ckpts ./pretrained/PoinTr_ShapeNet55.pth --config ./cfgs/ShapeNet55_models/PoinTr.yaml --mode easy --exp_name example
2022-12-14 10:25:40,482 - PoinTr - INFO - Copy the Config file from ./cfgs/ShapeNet55_models/PoinTr.yaml to ./experiments/PoinTr/ShapeNet55_models/test_example_easy/config.yaml
2022-12-14 10:25:40,482 - PoinTr - INFO - args.config : ./cfgs/ShapeNet55_models/PoinTr.yaml
2022-12-14 10:25:40,482 - PoinTr - INFO - args.launcher : none
2022-12-14 10:25:40,482 - PoinTr - INFO - args.local_rank : 0
2022-12-14 10:25:40,482 - PoinTr - INFO - args.num_workers : 4
2022-12-14 10:25:40,482 - PoinTr - INFO - args.seed : 0
2022-12-14 10:25:40,482 - PoinTr - INFO - args.deterministic : False
2022-12-14 10:25:40,482 - PoinTr - INFO - args.sync_bn : False
2022-12-14 10:25:40,482 - PoinTr - INFO - args.exp_name : test_example_easy
2022-12-14 10:25:40,482 - PoinTr - INFO - args.start_ckpts : None
2022-12-14 10:25:40,482 - PoinTr - INFO - args.ckpts : ./pretrained/PoinTr_ShapeNet55.pth
2022-12-14 10:25:40,482 - PoinTr - INFO - args.val_freq : 1
2022-12-14 10:25:40,482 - PoinTr - INFO - args.resume : False
2022-12-14 10:25:40,482 - PoinTr - INFO - args.test : True
2022-12-14 10:25:40,482 - PoinTr - INFO - args.mode : easy
2022-12-14 10:25:40,482 - PoinTr - INFO - args.experiment_path : ./experiments/PoinTr/ShapeNet55_models/test_example_easy
2022-12-14 10:25:40,482 - PoinTr - INFO - args.tfboard_path : ./experiments/PoinTr/ShapeNet55_models/TFBoard/test_example_easy
2022-12-14 10:25:40,482 - PoinTr - INFO - args.log_name : PoinTr
2022-12-14 10:25:40,482 - PoinTr - INFO - args.use_gpu : True
2022-12-14 10:25:40,482 - PoinTr - INFO - args.distributed : False
2022-12-14 10:25:40,482 - PoinTr - INFO - config.optimizer = edict()
2022-12-14 10:25:40,482 - PoinTr - INFO - config.optimizer.type : AdamW
2022-12-14 10:25:40,482 - PoinTr - INFO - config.optimizer.kwargs = edict()
2022-12-14 10:25:40,482 - PoinTr - INFO - config.optimizer.kwargs.lr : 0.0005
2022-12-14 10:25:40,482 - PoinTr - INFO - config.optimizer.kwargs.weight_decay : 0.0005
2022-12-14 10:25:40,483 - PoinTr - INFO - config.scheduler = edict()
2022-12-14 10:25:40,483 - PoinTr - INFO - config.scheduler.type : LambdaLR
2022-12-14 10:25:40,483 - PoinTr - INFO - config.scheduler.kwargs = edict()
2022-12-14 10:25:40,483 - PoinTr - INFO - config.scheduler.kwargs.decay_step : 21
2022-12-14 10:25:40,483 - PoinTr - INFO - config.scheduler.kwargs.lr_decay : 0.76
2022-12-14 10:25:40,483 - PoinTr - INFO - config.scheduler.kwargs.lowest_decay : 0.02
2022-12-14 10:25:40,483 - PoinTr - INFO - config.bnmscheduler = edict()
2022-12-14 10:25:40,483 - PoinTr - INFO - config.bnmscheduler.type : Lambda
2022-12-14 10:25:40,483 - PoinTr - INFO - config.bnmscheduler.kwargs = edict()
2022-12-14 10:25:40,483 - PoinTr - INFO - config.bnmscheduler.kwargs.decay_step : 21
2022-12-14 10:25:40,483 - PoinTr - INFO - config.bnmscheduler.kwargs.bn_decay : 0.5
2022-12-14 10:25:40,483 - PoinTr - INFO - config.bnmscheduler.kwargs.bn_momentum : 0.9
2022-12-14 10:25:40,483 - PoinTr - INFO - config.bnmscheduler.kwargs.lowest_decay : 0.01
2022-12-14 10:25:40,483 - PoinTr - INFO - config.dataset = edict()
2022-12-14 10:25:40,483 - PoinTr - INFO - config.dataset.train = edict()
2022-12-14 10:25:40,483 - PoinTr - INFO - config.dataset.train._base_ = edict()
2022-12-14 10:25:40,483 - PoinTr - INFO - config.dataset.train._base_.NAME : ShapeNet
2022-12-14 10:25:40,483 - PoinTr - INFO - config.dataset.train._base_.DATA_PATH : data/ShapeNet55-34/ShapeNet-55
2022-12-14 10:25:40,483 - PoinTr - INFO - config.dataset.train._base_.N_POINTS : 8192
2022-12-14 10:25:40,483 - PoinTr - INFO - config.dataset.train._base_.PC_PATH : data/ShapeNet55-34/shapenet_pc
2022-12-14 10:25:40,483 - PoinTr - INFO - config.dataset.train.others = edict()
2022-12-14 10:25:40,483 - PoinTr - INFO - config.dataset.train.others.subset : train
2022-12-14 10:25:40,484 - PoinTr - INFO - config.dataset.train.others.bs : 96
2022-12-14 10:25:40,484 - PoinTr - INFO - config.dataset.val = edict()
2022-12-14 10:25:40,484 - PoinTr - INFO - config.dataset.val._base_ = edict()
2022-12-14 10:25:40,484 - PoinTr - INFO - config.dataset.val._base_.NAME : ShapeNet
2022-12-14 10:25:40,484 - PoinTr - INFO - config.dataset.val._base_.DATA_PATH : data/ShapeNet55-34/ShapeNet-55
2022-12-14 10:25:40,484 - PoinTr - INFO - config.dataset.val._base_.N_POINTS : 8192
2022-12-14 10:25:40,484 - PoinTr - INFO - config.dataset.val._base_.PC_PATH : data/ShapeNet55-34/shapenet_pc
2022-12-14 10:25:40,484 - PoinTr - INFO - config.dataset.val.others = edict()
2022-12-14 10:25:40,484 - PoinTr - INFO - config.dataset.val.others.subset : test
2022-12-14 10:25:40,484 - PoinTr - INFO - config.dataset.test = edict()
2022-12-14 10:25:40,484 - PoinTr - INFO - config.dataset.test._base_ = edict()
2022-12-14 10:25:40,484 - PoinTr - INFO - config.dataset.test._base_.NAME : ShapeNet
2022-12-14 10:25:40,484 - PoinTr - INFO - config.dataset.test._base_.DATA_PATH : data/ShapeNet55-34/ShapeNet-55
2022-12-14 10:25:40,484 - PoinTr - INFO - config.dataset.test._base_.N_POINTS : 8192
2022-12-14 10:25:40,484 - PoinTr - INFO - config.dataset.test._base_.PC_PATH : data/ShapeNet55-34/shapenet_pc
2022-12-14 10:25:40,484 - PoinTr - INFO - config.dataset.test.others = edict()
2022-12-14 10:25:40,484 - PoinTr - INFO - config.dataset.test.others.subset : test
2022-12-14 10:25:40,484 - PoinTr - INFO - config.model = edict()
2022-12-14 10:25:40,484 - PoinTr - INFO - config.model.NAME : PoinTr
2022-12-14 10:25:40,484 - PoinTr - INFO - config.model.num_pred : 6144
2022-12-14 10:25:40,484 - PoinTr - INFO - config.model.num_query : 96
2022-12-14 10:25:40,484 - PoinTr - INFO - config.model.knn_layer : 1
2022-12-14 10:25:40,485 - PoinTr - INFO - config.model.trans_dim : 384
2022-12-14 10:25:40,485 - PoinTr - INFO - config.total_bs : 96
2022-12-14 10:25:40,485 - PoinTr - INFO - config.step_per_update : 1
2022-12-14 10:25:40,485 - PoinTr - INFO - config.max_epoch : 200
2022-12-14 10:25:40,485 - PoinTr - INFO - config.consider_metric : CDL2
2022-12-14 10:25:40,485 - PoinTr - INFO - Distributed training: False
2022-12-14 10:25:40,485 - PoinTr - INFO - Set random seed to 0, deterministic: False
2022-12-14 10:25:40,485 - PoinTr - INFO - Tester start ... 
[DATASET] Open file data/ShapeNet55-34/ShapeNet-55/test.txt
[DATASET] 3400 instances were loaded
2022-12-14 10:25:40,489 - MODEL - INFO -  Transformer with knn_layer 1
2022-12-14 10:25:42,161 - PoinTr - INFO - Loading weights from ./pretrained/PoinTr_ShapeNet55.pth...
2022-12-14 10:25:42,376 - PoinTr - INFO - ckpts @ 104 epoch( performance = No Metrics)
Traceback (most recent call last):
  File "main.py", line 68, in <module>
    main()
  File "main.py", line 62, in main
    test_net(args, config)
  File "/home/matthias/Netzwerke/PoinTr/tools/runner.py", line 304, in test_net
    test(base_model, test_dataloader, ChamferDisL1, ChamferDisL2, args, config, logger=logger)
  File "/home/matthias/Netzwerke/PoinTr/tools/runner.py", line 316, in test
    for idx, (taxonomy_ids, model_ids, data) in enumerate(test_dataloader):
  File "/home/matthias/Netzwerke/PoinTr/venv/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/home/matthias/Netzwerke/PoinTr/venv/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "/home/matthias/Netzwerke/PoinTr/venv/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/home/matthias/Netzwerke/PoinTr/venv/lib/python3.8/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/matthias/Netzwerke/PoinTr/venv/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/matthias/Netzwerke/PoinTr/venv/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/matthias/Netzwerke/PoinTr/venv/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/matthias/Netzwerke/PoinTr/datasets/ShapeNet55Dataset.py", line 44, in __getitem__
    data = IO.get(os.path.join(self.pc_path, sample['file_path'])).astype(np.float32)
  File "/home/matthias/Netzwerke/PoinTr/datasets/io.py", line 12, in get
    return cls._read_npy(file_path)
  File "/home/matthias/Netzwerke/PoinTr/datasets/io.py", line 25, in _read_npy
    return np.load(file_path)
  File "/home/matthias/Netzwerke/PoinTr/venv/lib/python3.8/site-packages/numpy/lib/npyio.py", line 405, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'data/ShapeNet55-34/shapenet_pc/02747177-ffe5f0ef45769204cb2a965e75be701c.npy'

**Comment by yuxumin** [comment]
Hi @matthiasjaeger95, 

> Is there maybe a wrong list of files or what could be the issue?

list is right, and i check the zip file, which is also complete.
Could you download the shapenet-pc again to ensure the issue is not due to some unexpected errors during download process?

**Comment by matthiasjaeger95** [comment]
Hello @yuxumin, 

that worked. I don't know why it didn't work on the first attempt but anyways that issue can be closed. Thank you.
